# Environment audit spec 
# Author: havembha@gmail.com,  2023-08-19
# Format
###
### you may use https://regex101.com/ to  test the regular expression definitions
###
---
LogFilePath: ./
### platform name or application name covering all components covered by this environment spec
### have one environment spec file per platform or application to manage many platforms/ application of an organization
Platform: Platform1

### Parameter name needs to be unique across all sections - OS, Component, and Environment
### Parameters can be defined under OS, Component or Environment.
### Parameter value can be redefined in other sections to override previous value defined in prior section(s).
### Parameters under OS will be read first, under Component next and under Environment last.
### While reading parameters under Component, if a value is present under specific component, 
###   it will be stored as latest desired value, overriding the value previously defined under OS
### While reading parameters under Environment, if a value is present under specific environment, 
###   it will be stored as latest desired value, overriding the value previously defined under OS or Component
### In all cases (OS, Component, Environment sections), value under 'All' will be stored 
###   if the value is not yet stored before in any prior section.
###
{% include "OSLevelVariableDefinitions.yml" %}

{% include "ComponentLevelVariableDefinitions.yml" %}

{% include "EnvironmentLevelVariableDefinitions.yml" %}
